name: Publish to FlexStudio Marketplace

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ENIAC-Tech/flex-plugin-actions/.github/workflows/publish.yml@v1.2.0
    with:
      flexcli-package: "https://github.com/ENIAC-Tech/flexcli/tarball/refs/heads/v2"
    secrets:
      webhook-secret: ${{ secrets.FLEX_MARKETPLACE_WEBHOOK_SECRET }}
